<?php
/**
 * Build-time asset manifest.
 *
 * A deploy step (`wp enqueues manifest build`) snapshots the expensive theme-tree scan into a single
 * PHP file at {theme}/dist/enqueues-manifest.php. Production requests then read one opcache-cached file
 * instead of walking the theme tree on every uncached request. Local dev never uses it (assets change
 * live, so scanning stays correct), and a signature mismatch makes a stale manifest fall back to
 * scanning automatically — so it is safe even if a deploy forgets to rebuild it.
 *
 * File Path: src/php/Function/Manifest.php
 *
 * @package Enqueues
 */

namespace Enqueues;

/**
 * Absolute path to the build-time asset manifest file.
 *
 * @return string
 */
function enqueues_manifest_path(): string {
	$directory = get_template_directory();
	$dist      = trim( (string) apply_filters( 'enqueues_asset_theme_dist_directory', 'dist' ), '/' );

	/**
	 * Filters the absolute path to the Enqueues build-time manifest.
	 *
	 * @param string $path The default path ({theme}/{dist}/enqueues-manifest.php).
	 */
	return (string) apply_filters( 'enqueues_manifest_path', "{$directory}/{$dist}/enqueues-manifest.php" );
}

/**
 * Loads the build-time asset manifest, or null to fall back to runtime scanning.
 *
 * Returns null when: running in local dev (is_local()), disabled via the `enqueues_manifest_enabled`
 * filter, the file is absent/unreadable, it is not an Enqueues manifest, or (unless disabled via
 * `enqueues_manifest_validate_signature`) its build signature does not match the current build.
 * Memoised per request.
 *
 * @return array|null
 */
function enqueues_manifest(): ?array {

	static $manifest = null;
	static $loaded   = false;

	if ( $loaded ) {
		return $manifest;
	}
	$loaded = true;

	// Never trust a build-time snapshot in local dev — assets change on every save. Also skip it in the
	// 'off' cache mode: the manifest is an optimisation tier, and is_request_memo_enabled() is true for
	// the request/persistent modes but false for off, so Off truly resolves every request (and pays no
	// signature-validation cost below). The enqueues_manifest_enabled filter can override either way.
	if ( is_local() || ! (bool) apply_filters( 'enqueues_manifest_enabled', is_request_memo_enabled() ) ) {
		return null;
	}

	$data = enqueues_read_asset_php( enqueues_manifest_path() );

	if ( empty( $data ) || empty( $data['enqueues_manifest'] ) ) {
		return null;
	}

	// Safety: ignore a manifest that does not match the current build (a deploy changed assets but the
	// manifest was not rebuilt) so stale data is never served. Filterable off for sites that always
	// rebuild the manifest on deploy and want to skip the signature computation entirely.
	if (
		(bool) apply_filters( 'enqueues_manifest_validate_signature', true )
		&& ( $data['signature'] ?? '' ) !== get_enqueues_build_signature()
	) {
		return null;
	}

	$manifest = $data;

	return $manifest;
}

/**
 * Returns a top-level section of the manifest (e.g. 'templates'), or null if unavailable.
 *
 * @param string $key The manifest section key.
 *
 * @return mixed|null
 */
function enqueues_manifest_get( string $key ) {
	$manifest = enqueues_manifest();

	return ( is_array( $manifest ) && array_key_exists( $key, $manifest ) ) ? $manifest[ $key ] : null;
}

/**
 * Generates the manifest data by scanning the filesystem fresh (bypassing cache and any existing
 * manifest). Used by `wp enqueues manifest build`.
 *
 * @return array
 */
function enqueues_manifest_generate(): array {
	$assets         = new \Enqueues\Library\EnqueueAssets();
	$templates      = $assets->build_theme_template_files_list();
	$blocks         = new \Enqueues\Controller\BlockEditorRegistrationController();
	$block_versions = $blocks->build_block_version_map();

	return [
		'enqueues_manifest' => true,
		'signature'         => get_enqueues_build_signature(),
		'generated'         => time(),
		'templates'         => array_values( $templates ),
		'block_versions'    => $block_versions,
	];
}

/**
 * Writes the manifest data to disk as a returnable PHP file.
 *
 * @param array $data The manifest data (see enqueues_manifest_generate()).
 *
 * @return bool True on success, false if the dist directory is missing or the write failed.
 */
function enqueues_manifest_write( array $data ): bool {
	$path = enqueues_manifest_path();

	if ( ! is_dir( dirname( $path ) ) ) {
		return false;
	}

	$php = "<?php\n/**\n * Auto-generated by `wp enqueues manifest build`. Do not edit.\n */\nreturn " . var_export( $data, true ) . ";\n";

	// Write to a per-process temp file then rename() — atomic on the same filesystem, so a concurrent
	// build or a reader never sees a torn file.
	$tmp = $path . '.' . getmypid() . '.tmp';
	if ( false === file_put_contents( $tmp, $php ) ) {
		return false;
	}

	if ( ! rename( $tmp, $path ) ) {
		@unlink( $tmp ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		return false;
	}

	return true;
}

/**
 * Removes the manifest file (runtime falls back to scanning).
 *
 * @return bool True if the file is gone (removed or never existed).
 */
function enqueues_manifest_clear(): bool {
	$path = enqueues_manifest_path();

	return file_exists( $path ) ? unlink( $path ) : true;
}
